[package]
name = "arxiv"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenvy = "0.15.7"
reqwest = { version = "0.12.12", features = ["blocking"] }
quick-xml = { version = "0.37.2", features = ["serialize"] }
serde = { version = "1.0.217", features = ["derive"] }
